package:
  name: error_tools
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build . --target error_tools
    - cmake --install . --prefix $PREFIX
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools_scm >=6.2
  host:
    - {{ compiler('cxx') }}
    - python
    - cmake >=3.18
    - eigen >=3.3.7
    - boost >=1.59  # TODO: Separate the package/test configuration to make BOOST an optional build dependency
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  run:
    - {{ compiler('cxx') }}
    - eigen >=3.3.7

test:
  requires:
    - cmake >=3.18
    - boost >=1.59
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_error_tools.cpp
  commands:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build . --target test_error_tools
    - ctest -R test_error_tools
