workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

before_script:
  # TODO: recover environment path from modulefile instead of assuming the sstelmo path(s)
  # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/7
  - aea_projects='/projects'
  - aea_deploy_directory="${aea_projects}/aea_compute"
  - aea_conda_channel="${aea_deploy_directory}/aea-conda"
  - aea_modulefiles=${aea_deploy_directory}/modulefiles
  - environment='aea-beta'
  - environment_path="${aea_deploy_directory}/${environment}"
  - conda_options='--yes --channel conda-forge'
  # Activate the project specific environment from the project specific modulefile
  - module use ${aea_deploy_directory}/modulefiles
  - module load ${environment}
  # TODO: Add minimal project environment build, modulfile, and activation
  # FIXME: (1) Without setting this to false, Git webserver API calls to re-git.lanl.gov will throw errors about
  # self-signed certificates. Work on CI server and Gitlab webserver configurations so that this is no longer
  # necessary. There is a matching "FIXME: (1)" tag where the process is reversed that must also be removed when this
  # is fixed.
  - git config --local http.sslVerify false

after_script:
  # FIXME: (1) Reset the repository Git configuration to preserve ssl verifications. Remove when the server(s)
  # configurations no longer require us to drop ssl verifications.
  - git config --local http.sslVerify true

conda-build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    # Set the LANL internal proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    - output_folder='conda-build-artifacts'
    - mkdir ${output_folder}
    - VERSION=$(python -m setuptools_scm) conda build recipe --channel conda-forge --no-anaconda-upload --croot /scratch/${USER}/conda-build --output-folder ${output_folder} --no-test
  artifacts:
    expire_in: '2 hrs'
    paths:
      - conda-build-artifacts/noarch/error_tools-*-*.tar.bz2
  tags:
    - sstelmo-shell-aea
  only:
    - merge_requests
    - main
    - dev

test_build:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    GIT_STRATEGY: clone
  script: ./CI.sh
  artifacts:
    when: always
    paths:
      - build/results.tex
  tags:
    - sstelmo-shell-aea

deploy_build:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script: ./CD.sh
  tags:
    - sstelmo-shell-aea
  only:
    - master
    - dev

# It MUST be called pages
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - ./BUILD.sh
    - mkdir public
    - cp -r build/docs/sphinx/html/* public/
  artifacts:
    paths:
      # It MUST be called public
      - public
  tags:
    - sstelmo-shell-aea
  only:
    - master
